validation: sovereign
version: 1
chain_id: "narwhal-1"
accounts:
- name: smoothiepool
  coins:
  - 400000000000narwhal
- name: faucet
  coins:
  - 100000000narwhal
faucet:
  name: faucet
  coins:
  - 100000narwhal
client:
  source_url: "https://github.com/uwu-shepards/narwhal"
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml
validators:
- name: smoothiepool
  bonded: 200000000000narwhal
